# Development Docker Compose Override
# Copy this file to docker-compose.override.yml and customize for your development
# This file allows each developer to have their own database and settings

version: '3.8'

services:
  # PostgreSQL Database (Development)
  postgres:
    environment:
      POSTGRES_DB: wardenprime_dev_${DEV_NAME:-developer}
      POSTGRES_USER: ${DEV_NAME:-developer}
      POSTGRES_PASSWORD: ${DEV_PASSWORD:-dev_password}
    volumes:
      - postgres_data_${DEV_NAME:-developer}:/var/lib/postgresql/data
    ports:
      - "${PG_PORT:-5432}:5432"

  # Discord Bot (Development)
  bot:
    environment:
      # Development settings
      NODE_ENV: development
      LOG_LEVEL: DEBUG
      
      # Database (use your own)
      PG_DATABASE: wardenprime_dev_${DEV_NAME:-developer}
      PG_USER: ${DEV_NAME:-developer}
      PG_PASSWORD: ${DEV_PASSWORD:-dev_password}
      
      # Bot settings
      BOT_NAME: WardenPrime-Dev
      EMBED_FOOTER: Powered by WardenPrime (Dev)
      
      # Command deployment (guild-specific for development)
      COMMAND_DEPLOYMENT_MODE: guild
      DEPLOYMENT_GUILD_IDS: ${TEST_GUILD_ID}
      
      # Dashboard (useful for development)
      DASHBOARD_ENABLED: true
      DASHBOARD_PORT: ${DASHBOARD_PORT:-3080}
      DASHBOARD_SESSION_SECRET: ${DEV_SESSION_SECRET:-dev_session_secret}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "${DASHBOARD_PORT:-3080}:3080"

  # Dashboard (Development)
  dashboard:
    environment:
      NODE_ENV: development
      DASHBOARD_PORT: ${DASHBOARD_PORT:-3080}
      DASHBOARD_SESSION_SECRET: ${DEV_SESSION_SECRET:-dev_session_secret}
    ports:
      - "${DASHBOARD_PORT:-3080}:3080"
    profiles:
      - dashboard

volumes:
  postgres_data_${DEV_NAME:-developer}:
    driver: local
