@echo off
REM WardenPrime Development Setup Script for Windows
REM This script helps set up the development environment for multiple developers

echo.
echo 🚀 WardenPrime Development Setup
echo ================================
echo.

REM Check if we're in the right directory
if not exist "package.json" (
    echo ❌ Please run this script from the WardenPrime root directory
    pause
    exit /b 1
)

echo 👤 Developer Setup
echo ==================
set /p DEV_NAME="Enter your name (for database isolation): "
set /p BOT_TOKEN="Enter your Discord bot token: "
set /p CLIENT_ID="Enter your Discord client ID: "
set /p TEST_GUILD_ID="Enter your test guild ID: "
set /p BOT_OWNER_ID="Enter your Discord user ID (bot owner): "

REM Generate random passwords (simple method)
set DEV_PASSWORD=%RANDOM%%RANDOM%%RANDOM%
set DEV_SESSION_SECRET=%RANDOM%%RANDOM%%RANDOM%%RANDOM%

echo.
echo 📝 Creating development environment file...

REM Create .env file
(
echo # ===========================================
echo # WardenPrime Development Environment
echo # ===========================================
echo # Generated by setup-dev.bat on %date% %time%
echo.
echo # Developer Information
echo DEV_NAME=%DEV_NAME%
echo DEV_PASSWORD=%DEV_PASSWORD%
echo DEV_SESSION_SECRET=%DEV_SESSION_SECRET%
echo.
echo # Discord Bot Configuration
echo BOT_TOKEN=%BOT_TOKEN%
echo CLIENT_ID=%CLIENT_ID%
echo TEST_GUILD_ID=%TEST_GUILD_ID%
echo BOT_OWNER_ID=%BOT_OWNER_ID%
echo.
echo # Bot Customization
echo BOT_NAME=WardenPrime-Dev
echo BOT_PREFIX=!
echo EMBED_COLOR=5865F2
echo EMBED_FOOTER=Powered by WardenPrime ^(Dev^)
echo.
echo # Feature Flags
echo ENABLE_COOLDOWNS=true
echo ENABLE_MENTIONS=true
echo ENABLE_LOGGING=true
echo LOG_LEVEL=DEBUG
echo SKIP_COMMAND_REGISTRATION=false
echo.
echo # Command Deployment ^(guild-specific for development^)
echo COMMAND_DEPLOYMENT_MODE=guild
echo DEPLOYMENT_GUILD_IDS=%TEST_GUILD_ID%
echo.
echo # Database Configuration
echo DATABASE_TYPE=postgres
echo PG_HOST=postgres
echo PG_PORT=5432
echo PG_DATABASE=wardenprime_dev_%DEV_NAME%
echo PG_USER=%DEV_NAME%
echo PG_PASSWORD=%DEV_PASSWORD%
echo PG_SSL_MODE=disable
echo.
echo # Dashboard Configuration
echo DASHBOARD_ENABLED=true
echo DASHBOARD_PORT=3080
echo DASHBOARD_PUBLIC_URL=http://localhost:3080
echo DASHBOARD_SESSION_SECRET=%DEV_SESSION_SECRET%
echo OAUTH_CALLBACK_URL=http://localhost:3080/auth/callback
echo.
echo # Environment
echo NODE_ENV=development
) > .env

echo ✅ Created .env file

REM Create docker-compose override
echo 📝 Creating Docker Compose override...
copy docker-compose.dev.yml docker-compose.override.yml >nul

echo ✅ Created docker-compose.override.yml

REM Create necessary directories
echo 📁 Creating directories...
if not exist "logs" mkdir logs
if not exist "data" mkdir data

echo ✅ Created directories

echo.
echo 🎉 Development setup complete!
echo.
echo 📋 Your development environment:
echo    Developer: %DEV_NAME%
echo    Database: wardenprime_dev_%DEV_NAME%
echo    Dashboard: http://localhost:3080
echo    Bot Name: WardenPrime-Dev
echo.
echo 🚀 To start development:
echo    docker-start.bat
echo.
echo 📝 Important notes:
echo    - Your .env file contains sensitive data - don't commit it!
echo    - Each developer should have their own Discord bot
echo    - Use guild deployment mode to avoid command conflicts
echo    - Your database is isolated from other developers
echo.
pause
