#!/bin/bash

# WardenPrime Development Setup Script
# This script helps set up the development environment for multiple developers

set -e

echo "🚀 WardenPrime Development Setup"
echo "================================"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Please run this script from the WardenPrime root directory"
    exit 1
fi

# Get developer name
echo "👤 Developer Setup"
echo "=================="
read -p "Enter your name (for database isolation): " DEV_NAME
read -p "Enter your Discord bot token: " BOT_TOKEN
read -p "Enter your Discord client ID: " CLIENT_ID
read -p "Enter your test guild ID: " TEST_GUILD_ID
read -p "Enter your Discord user ID (bot owner): " BOT_OWNER_ID

# Generate random passwords
DEV_PASSWORD=$(openssl rand -base64 12 | tr -d "=+/" | cut -c1-16)
DEV_SESSION_SECRET=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)

echo ""
echo "📝 Creating development environment file..."

# Create .env file
cat > .env << EOF
# ===========================================
# WardenPrime Development Environment
# ===========================================
# Generated by setup-dev.sh on $(date)

# Developer Information
DEV_NAME=${DEV_NAME}
DEV_PASSWORD=${DEV_PASSWORD}
DEV_SESSION_SECRET=${DEV_SESSION_SECRET}

# Discord Bot Configuration
BOT_TOKEN=${BOT_TOKEN}
CLIENT_ID=${CLIENT_ID}
TEST_GUILD_ID=${TEST_GUILD_ID}
BOT_OWNER_ID=${BOT_OWNER_ID}

# Bot Customization
BOT_NAME=WardenPrime-Dev
BOT_PREFIX=!
EMBED_COLOR=5865F2
EMBED_FOOTER=Powered by WardenPrime (Dev)

# Feature Flags
ENABLE_COOLDOWNS=true
ENABLE_MENTIONS=true
ENABLE_LOGGING=true
LOG_LEVEL=DEBUG
SKIP_COMMAND_REGISTRATION=false

# Command Deployment (guild-specific for development)
COMMAND_DEPLOYMENT_MODE=guild
DEPLOYMENT_GUILD_IDS=${TEST_GUILD_ID}

# Database Configuration
DATABASE_TYPE=postgres
PG_HOST=postgres
PG_PORT=5432
PG_DATABASE=wardenprime_dev_${DEV_NAME}
PG_USER=${DEV_NAME}
PG_PASSWORD=${DEV_PASSWORD}
PG_SSL_MODE=disable

# Dashboard Configuration
DASHBOARD_ENABLED=true
DASHBOARD_PORT=3080
DASHBOARD_PUBLIC_URL=http://localhost:3080
DASHBOARD_SESSION_SECRET=${DEV_SESSION_SECRET}
OAUTH_CALLBACK_URL=http://localhost:3080/auth/callback

# Environment
NODE_ENV=development
EOF

echo "✅ Created .env file"

# Create docker-compose override
echo "📝 Creating Docker Compose override..."
cp docker-compose.dev.yml docker-compose.override.yml

echo "✅ Created docker-compose.override.yml"

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p logs data

echo "✅ Created directories"

echo ""
echo "🎉 Development setup complete!"
echo ""
echo "📋 Your development environment:"
echo "   Developer: ${DEV_NAME}"
echo "   Database: wardenprime_dev_${DEV_NAME}"
echo "   Dashboard: http://localhost:3080"
echo "   Bot Name: WardenPrime-Dev"
echo ""
echo "🚀 To start development:"
echo "   ./docker-start.sh"
echo ""
echo "📝 Important notes:"
echo "   - Your .env file contains sensitive data - don't commit it!"
echo "   - Each developer should have their own Discord bot"
echo "   - Use guild deployment mode to avoid command conflicts"
echo "   - Your database is isolated from other developers"
echo ""
